# This is a sample Python script.

# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.
from graphviz import Digraph
def draw():

    g = Digraph('Pratylenchus Key', comment="FOO",filename = 'PratylenchusKey.gv')#, node_attr={'color': 'lightblue2', 'style': 'filled'} )
    #g.graph_attr(labelloc="t")
    #g.graph_attr(label="My Diagram")
    #g.attr(size='6,6')
    g.graph_attr['rankdir'] = 'LR'

    g.node('001', label='Key to Pratylenchidae\nan adapatation from:\n\nPratylenchus (Nematoda:\nPratylenchidae): Diagnosis, Biology,\nPathpgenicity And Management\n\nPablo Castillo et al',fillcolor='red',style="filled")
    g.node('001.1', 'Labial region\nannuli',fillcolor='aqua',style="filled" )
    g.edge('001','001.1')

    g.edge('001.1','002', label='Two')
    g.edge('001.1','028', label='Three')
    g.edge('001.1','065', label='Four')
    g.node('002', 'Males',fillcolor='aqua',style="filled")
    g.edge('002','003', label='Absent')
    g.edge('002','008', label='Common\n(Spermatheca\nfilled with sperm)')
    g.node('P. angulatus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('003', 'Stylet',fillcolor='aqua',style="filled" )
    g.edge('003','P. angulatus', label='< 13 μm')
    g.edge('003','004', label='> 13 μm')
    g.node('P. acuticaudatus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('004', 'Spermatheca', fillcolor='aqua',style="filled")
    g.edge('004','P. acuticaudatus', label='Absent or reduced')
    g.edge('004','005', label='Well developed')
    g.node('P. crassi', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('005', 'Vulva',fillcolor='aqua',style="filled" )
    g.edge('005','P. crassi', label='< 75%')
    g.edge('005','006', label='&#8805; 75%')
    g.node('006', 'Post-vulval\nuterine sac', fillcolor='aqua',style="filled" )
    g.edge('006','007', label='< 16 μm')
    g.node('P. hippeastri', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('006','P. hippeastri', label='30-35 μm')
    g.node('P. tenuis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('007', 'Female\ntail', fillcolor='aqua',style="filled" )
    g.edge('007','P. tenuis', label='Tip smooth')
    g.node('P. estoniensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('007','P. estoniensis', label='Tip striated')
    g.node('P. macrostylus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('008', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('008','P. macrostylus', label='> 20 μm')
    g.edge('008','009', label='< 20 μm')
    g.node('009', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('009','010', label='18-20 μm')
    g.edge('009','011', label='< 18 μm')
    g.node('P. brachyurus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('010', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('010','P. brachyurus', label='Reduced,\nlabial region offset\n from body,\nwith angular anterior margin')
    g.node('P. brzeskii', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('010','P. brzeskii', label='Developed,\nrectangular')
    g.node('011', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('011','012', label='16-17.9 μm')
    g.edge('011','018', label='< 16 μm')
    g.node('P. neglectus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('012', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('012','P. neglectus', label='Reduced,\nsecond annulus of labial\nregion wider than first')
    g.edge('012','013', label='Developed')
    g.node('013', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('013','014', label='Rounded to spherical')
    g.edge('013','015', label='oval or rectangular')
    g.node('P. flakkensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('P. dunensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('014', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('014','P. flakkensis', label='< 20 μm')
    g.edge('014','P. dunensis', label='25-30 μm')
    g.node('P. yamagutii', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('015', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('015','P. yamagutii', label='< 16 μm')
    g.edge('015','016', label='> 16 μm')
    g.node('P. panamaensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('016', 'Female\ntail', fillcolor='aqua',style="filled" )
    g.edge('016','P. panamaensis', label='Subcylindrical')
    g.edge('016','017', label='Conoid')
    g.node('P. loosi', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('017', 'Pharyngeal overlap', fillcolor='aqua',style="filled" )
    g.edge('017', 'P. loosi', label='< 40 μm,\n labial region rounded,\nspermathecarectangular,\ntail tapering gradually\nto smooth conical tip,\n usually with narrowly rounded terminus,\n males abundant')
    g.node('P. okinawensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('017','P. okinawensis', label='> 50 μm')
    g.node('P. hexincisus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('018', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('018','P. hexincisus', label='Reduced,\nlateral fields with six\nlines on most of body')
    g.edge('018','019', label='Developed')
    g.node('018', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('019','020', label='Rounded to \nspherical')
    g.edge('019','024', label='Oval')
    g.node('P. gibbicaudatus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('020','P. gibbicaudatus', label='Vulva position < 75%')
    g.node('020', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('020','021', label='> 75%')
    g.node('021', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('021','022', label='< 20 μm')
    g.node('P. jaehni', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('021','P. jaehni', label='Post-vulval uterine sac > 20 μm')
    g.node('P. silvaticus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('022', 'Female\ntail ', fillcolor='aqua',style="filled" )
    g.edge('022','P. silvaticus', label='Conoid')
    g.edge('022','023', label='Subcylindrical')
    g.node('P. alleni', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('023', 'Female\ntail tip ', fillcolor='aqua',style="filled" )
    g.edge('023','P. alleni', label='smooth')
    g.node('P. roseus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('023','P. roseus', label='Striated')
    g.node('024', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('024','025', label='< 75%')
    g.edge('024','026', label='> 75%')
    g.node('P. artemisiae', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('025', 'Female\ntail ', fillcolor='aqua',style="filled" )
    g.edge('025','P. artemisiae', label='Subcylindrical')
    g.node('P. scribneri', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('025','P. scribneri', label='Conoid,\nlabial region slightly\noffset from body,\n stylet stout,\nwith rounded knobs, \nspermatheca oblong, \ntail tapering slightly \nwith smooth terminus')
    g.node('P. neobrachyurus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('026', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('026','P. neobrachyurus', label='< 16 μm')
    g.edge('026','027', label='Post-vulval uterine sac > 16 μm')
    g.node('P. coffeae', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('027', 'Pharyngeal\noverlap ', fillcolor='aqua',style="filled" )
    g.edge('027','P. coffeae', label='< 40 μm,\n labial region slightly offset,\n postvulval uterine sac 1.0-1.5 \nbody diam. long with a terminal rudimentary ovary, \nfemale tail tip truncate or hemispherical')
    g.node('P. pseudocoffeae', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('027','P. pseudocoffeae', label='Pharyngeal overlap > 50 μm')
    g.node('028', 'Males', fillcolor='aqua',style="filled" )
    g.edge('028','029', label='Absent,\nspermatheca empty')
    g.edge('028','043', label='Common,\nspermatheca filled with sperm')
    g.node('P. microstylus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('029', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('029','P. microstylus', label='< 13 μm')
    g.edge('029','030', label='> 13 μm')
    g.node('030', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('030','031', label='18-20 μm')
    g.edge('030','032', label='< 18 μm')
    g.node('P. japonicus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('031', 'Post-vulva\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('031','P. japonicus', label='< 20 μm')
    g.node('P. bolivianus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('031','P. bolivianus', label='> 20 μm')
    g.node('032', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('032','033', label='< 16 μm')
    g.edge('032','037', label='> 16 μm')
    g.node('033', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('033','034', label='Reduced or\n absent')
    g.node('P. elamini', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('033','P. elamini', label='Oval')
    g.node('P. teres', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('034', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('034','P. teres', label='< 75%')
    g.edge('034','035', label='> 75%')
    g.node('035', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('035','036', label='< 25 μm')
    g.node('P. sensillatus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('035','P. sensillatus', label='> 25 μm')
    g.node('P. cruciferus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('036', 'Female\ntail tip', fillcolor='aqua',style="filled" )
    g.edge('036','P. cruciferus', label='Smooth')
    g.node('P. kumaoensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('036','P. kumaoensis', label='Striated')
    g.node('037', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('037','038', label='Reduced or\nabsent')
    g.edge('037','041', label='Developed')
    g.node('P. curvicauda', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('038', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('038','P. curvicauda', label='< 75%')
    g.edge('038','039', label='> 75%')
    g.node('P. pinguicaudatus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('039', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('039','P. pinguicaudatus', label='< 16 μm')
    g.edge('039','040', label='> 20 μm')
    g.node('P. delattrei', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('040', 'Female\ntail tip ', fillcolor='aqua',style="filled" )
    g.edge('040','P. delattrei', label='smooth')
    g.node('P. subranjani', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('040','P. subranjani', label='Striated')
    g.node('P. yassini', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('041', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('041','P. yassini', label='< 75%')
    g.edge('041','042', label='> 75%')
    g.node('P. arlingtoni', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('042', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('042','P. arlingtoni', label='shorter\nthan 20 μm')
    g.node('P. andinus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('042','P. andinus', label='Post-vulval uterine \nsac longer than 20 μm')
    g.node('P. ekrami', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('043', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('043','P. ekrami', label='< 13 μm')
    g.edge('043','044', label='> 13 μm')
    g.node('044', 'Stylet', fillcolor='aqua',style="filled" )
    g.edge('044','045', label='< 16 μm')
    g.edge('044','055', label='> 16 μm')
    g.node('045', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('045','046', label='Rounded to\nspherical')
    g.edge('045','049', label='Oval or\nrectangular')
    g.node('P. bhattii', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('046', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('046','P. bhattii', label='< 75%')
    g.edge('046','047', label='> 75%')
    g.node('P. kralli', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('047', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('047','P. kralli', label='< 16 μm')
    g.edge('047','048', label='> 16 μm')
    g.node('P. mediterraneus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('048', 'Female\ntail tip', fillcolor='aqua',style="filled" )
    g.edge('048','P. mediterraneus', label='Smooth')
    g.node('P. pseudofallax', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('048','P. pseudofallax', label='Striated')
    g.node('049', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('049','050', label='Oval')
    g.edge('049','053', label='Rectangular')
    g.node('P. sudanensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('050', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('050','P. sudanensis', label='< 75%')
    g.edge('050','051', label='> 75%')
    g.node('051', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('051','P. vulnus', label='> 30 μm,\nlabial region almost\ncontinuous with body contour,\npharynx overlapping intestine\n in a long lobe spermatheca oblong,\npost-vulval uterine sac ca 2\nvulval body diam. long\nwith rudimentary ovary, \ntail tapering, \nwith narrowly rounded to subacute smooth tip')
    g.edge('051','052', label='< 30 μm')
    g.node('052', 'Female\ntail tip', fillcolor='aqua',style="filled" )
    g.edge('052','P. unzenensis', label='Smooth')
    g.edge('052','P. pratensisobrinus', label='Striated')
    g.node('053', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('053','054', label='< 80%.')
    g.node('P. manaliensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('053','P. manaliensis', label='80-85%')
    g.node('P. pratensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('054', 'Female\ntail tip ', fillcolor='aqua',style="filled" )
    g.edge('054','P. pratensis', label='Striated, \ncuticle finely annulated, \noval to rectangular spermatheca, \npost-vulval uterine sac \nlength similar to body diam.,\ntail annulated until terminus')
    g.edge('054','Female tail tip with a ventral projection', label='P. ventroprojectus')
    g.node('055', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('055','056', label='Reduced or\nabsent')
    g.edge('055','058', label='Developed')
    g.node('P. zeae', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('056', 'Vulva', fillcolor='aqua',style="filled" )
    g.edge('056','P. zeae', label='< 76%,\nspermatheca round, \nvulva at 68-76%, tail \nconoid, terminus generally almost pointed, \nnarrowly rounded to subacute, unstriated')
    g.edge('056','057', label='> 76%.')
    g.node('P. thornei', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('057', 'Female\ntail tip', fillcolor='aqua',style="filled" )
    g.edge('057','P. thornei', label='Smooth, \nlabial region not offset from body, \nouter margin of sclerotised labial \nframework conspicuously\nextending ca two annuli \ninto body and 1 annulus into labial region, \nlateral fields with four lines, \nthe outer ones straight or\nweakly crenate, \nstylet medium size (17-19 μm long), \nspermatheca difficult to see, \nnot containing spermatozoa, \nmales very rare')
    g.node('P. crenatus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('057','P. crenatus', label='Striated')
    g.node('058', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('058','059', label='Rounded to\nspherical')
    g.edge('058','062', label='Oval')
    g.node('059', 'Post-vulval\nuterine sac', fillcolor='aqua',style="filled" )
    g.edge('059','P. convallariae', label='> 35 μm')
    g.edge('059','060', label='25-35 μm')
    g.node('P. penetrans', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('060', 'Female\ntail tip', fillcolor='aqua',style="filled" )
    g.edge('060','P. penetrans', label='Smooth, \nlabial region slightly offset, low, \nflat in front, \nwith rounded outer margins, \npharynx overlapping intestine\nin a lobe ca 1.5 body diam. long, \npost-vulval uterine sac short,\n undifferentiated and tail generally rounded, \ntip smooth')
    g.edge('060','061', label='Striated')
    g.node('P. pseudopratensis', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('061', 'Spermatheca', fillcolor='aqua',style="filled" )
    g.edge('061','P. pseudopratensis', label='Rectangular,\nfemale tail tip rounded to truncate,\nsmooth')
    g.edge('061','P. fallax', label='Spermatheca rounded, \nfemale tail tip rounded, \nsmooth or slightly irregular contour')
    g.node('P. morettoi', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('062', 'Post-vulval\nuterine sac', fillcolor='aqua',style="filled" )
    g.edge('062','P. morettoi', label='> 35 μm')
    g.edge('062','063', label='< 35 μm')
    g.node('063', 'Female\ntail tip', fillcolor='aqua',style="filled" )
    g.edge('063','064', label='Smooth')
    g.node('P. kasari', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('063','P. kasari', label='Striated')
    g.node('P. subpenetrans', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('064', 'Post-vulval\nuterine sac ', fillcolor='aqua',style="filled" )
    g.edge('064','P. subpenetrans', label='< 20 μm')
    g.node('P. mulchandi', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('064','P. mulchandi', label='> 30 μm')
    g.node('065', 'Males', fillcolor='aqua',style="filled" )
    g.edge('065','066', label='Absent,\nspermatheca empty')
    g.node('P. goodeyi', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('065','P. goodeyi', label='Common, \nspermatheca filled with sperm, \nlateral fields with four inconspicuous lines, \nthe two outer bands partially areolated, \ntail conoid, ventrally concave')
    g.node('P. typicus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.node('066', 'Post-vulval\nuterine sac', fillcolor='aqua',style="filled" )
    g.edge('066','P. typicus', label='> 30 μm')
    g.node('P. wescolagricus', shape='doubleoctagon', color='blue', fillcolor='aquamarine3',style="rounded,filled")
    g.edge('066','P. wescolagricus', label='< 30 μm')


    g.render('PratylenchusKey.gv', format='svg', view=True)
    g.render('PratylenchusKey.gv', format='jpg', view=False)

def main():
    # Use a breakpoint in the code line below to debug your script.
    draw()


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    main()

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
